// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions? tryCurrentPlatform() {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return null;
      default:
        return null;
    }
  }

  static FirebaseOptions get currentPlatform =>
      tryCurrentPlatform() ??
      (throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.'));

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1DU3VEY5TtE_EZz7ZHN6NyoFfxycTOHA',
    appId: '1:728164013745:web:fbfcddcb53abfbe1663490',
    messagingSenderId: '728164013745',
    projectId: 'revv-eb7c9',
    authDomain: 'revv-eb7c9.firebaseapp.com',
    storageBucket: 'revv-eb7c9.firebasestorage.app',
    measurementId: 'G-HH0FSPHF0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5XCSo5Gz4e0gnc7IO0YoN1Hx-uElJoTc',
    appId: '1:728164013745:android:4edee6329b4f3c92663490',
    messagingSenderId: '728164013745',
    projectId: 'revv-eb7c9',
    storageBucket: 'revv-eb7c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXO_vjhvNCUBpSFYTegFmXthg95uUrt6o',
    appId: '1:728164013745:ios:742c636b30914700663490',
    messagingSenderId: '728164013745',
    projectId: 'revv-eb7c9',
    storageBucket: 'revv-eb7c9.firebasestorage.app',
    iosBundleId: 'com.revv.revvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXO_vjhvNCUBpSFYTegFmXthg95uUrt6o',
    appId: '1:728164013745:ios:742c636b30914700663490',
    messagingSenderId: '728164013745',
    projectId: 'revv-eb7c9',
    storageBucket: 'revv-eb7c9.firebasestorage.app',
    iosBundleId: 'com.revv.revvApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1DU3VEY5TtE_EZz7ZHN6NyoFfxycTOHA',
    appId: '1:728164013745:web:a1036d3fac7996f2663490',
    messagingSenderId: '728164013745',
    projectId: 'revv-eb7c9',
    authDomain: 'revv-eb7c9.firebaseapp.com',
    storageBucket: 'revv-eb7c9.firebasestorage.app',
    measurementId: 'G-WV2WC72T72',
  );
}
